package me.rerere.workspace

import java.io.File
import java.nio.file.Files

fun ensureRootfsDns(
    linuxDir: File,
    nameservers: List<String> = DEFAULT_DNS_SERVERS,
) {
    val etcDir = File(linuxDir, "etc")
    if (!etcDir.isDirectory) return
    val resolvConf = File(etcDir, "resolv.conf")
    val shouldWrite = when {
        Files.isSymbolicLink(resolvConf.toPath()) -> true
        !resolvConf.exists() -> true
        !resolvConf.isFile -> true
        else -> resolvConf.readText()
            .lineSequence()
            .filter { it.trimStart().startsWith("nameserver ") }
            .none { line ->
                val server = line.trim().removePrefix("nameserver").trim()
                server.isNotBlank() && server !in LOCAL_RESOLVERS
            }
    }
    if (!shouldWrite) return

    if (resolvConf.exists() || Files.isSymbolicLink(resolvConf.toPath())) {
        resolvConf.delete()
    }

    val servers = nameservers
        .filter { it.isNotBlank() }
        .distinct()
        .take(MAX_DNS_SERVERS)
        .ifEmpty { DEFAULT_DNS_SERVERS }

    resolvConf.writeText(
        buildString {
            appendLine("# Generated by RikkaHub workspace.")
            servers.forEach { appendLine("nameserver $it") }
            appendLine("options edns0 trust-ad")
        }
    )
}

private const val MAX_DNS_SERVERS = 3

private val LOCAL_RESOLVERS = setOf(
    "127.0.0.1",
    "127.0.0.53",
    "::1",
)

private val DEFAULT_DNS_SERVERS = listOf(
    "1.1.1.1",
    "8.8.8.8",
    "223.5.5.5",
)
