#!/usr/bin/env bash
# install-perry.sh — install a global `perry` command that points at this server tree.
#
# Run from Perry server root (directory containing pyproject.toml):
#   cd /home/purbliss/src/haruhome/server
#   ./scripts/install-perry.sh
#
# Then anywhere:
#   perry          # admin TUI
#   perry start    # background server
#   perry stop
#   perry wipe
#   perry bootstrap
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ ! -f "$ROOT/pyproject.toml" ]]; then
  echo "ERROR: not a Perry server root: $ROOT" >&2
  exit 1
fi

if [[ ! -f "$ROOT/scripts/perry" ]]; then
  echo "ERROR: missing $ROOT/scripts/perry" >&2
  exit 1
fi

chmod +x "$ROOT/scripts/perry" "$ROOT/scripts/install-perry.sh" 2>/dev/null || true
# optional legacy script
[[ -f "$ROOT/scripts/wipe-sync-data.sh" ]] && chmod +x "$ROOT/scripts/wipe-sync-data.sh" || true

BIN_DIR="${PERRY_BIN_DIR:-$HOME/.local/bin}"
mkdir -p "$BIN_DIR"

WRAPPER="$BIN_DIR/perry"
cat >"$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by install-perry.sh — do not edit by hand.
export PERRY_HOME="$ROOT"
exec "$ROOT/scripts/perry" "\$@"
EOF
chmod +x "$WRAPPER"

# Prefer LF on Windows-mounted trees when possible
if command -v sed >/dev/null 2>&1; then
  sed -i 's/\r$//' "$WRAPPER" 2>/dev/null || true
  sed -i 's/\r$//' "$ROOT/scripts/perry" 2>/dev/null || true
fi

echo "✔ Installed global command: $WRAPPER"
echo "  PERRY_HOME=$ROOT"
echo

# PATH check
case ":$PATH:" in
  *":$BIN_DIR:"*)
    echo "✔ $BIN_DIR already on PATH"
    ;;
  *)
    echo "⚠ $BIN_DIR is not on PATH."
    echo "  Add this to ~/.bashrc or ~/.zshrc:"
    echo "    export PATH=\"$BIN_DIR:\$PATH\""
    echo
    # best-effort append for bash
    if [[ -f "$HOME/.bashrc" ]] && ! grep -q 'export PATH=.*\.local/bin' "$HOME/.bashrc" 2>/dev/null; then
      read -r -p "Append PATH export to ~/.bashrc now? [y/N] " ans || true
      if [[ "${ans:-}" == "y" || "${ans:-}" == "Y" ]]; then
        {
          echo ""
          echo "# Perry CLI"
          echo "export PATH=\"$BIN_DIR:\$PATH\""
        } >>"$HOME/.bashrc"
        echo "✔ appended to ~/.bashrc (open a new shell or: source ~/.bashrc)"
      fi
    fi
    ;;
esac

echo
echo "Try:"
echo "  perry status"
echo "  perry start"
echo "  perry          # TUI"
echo
if [[ ! -f "$ROOT/.env" ]]; then
  echo "No .env yet — run: perry init"
fi
