name: Build APK
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test KEY_BASE64
        run: echo "${{ secrets.KEY_BASE64 }}" | head -c 10
