name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Gradle Build
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: artifacts
          path: app/build/outputs/apk/release/*.apk

      - name: Create Release and Upload APKs
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
          generate_release_notes: true
          draft: false
          prerelease: false
